# localstack config from repo https://github.com/localstack/localstack/blob/master/docker-compose.yml
# https://docs.localstack.cloud/get-started/#docker
version: "3.8"

services:
  app:
    image: 'aws-project:10'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"    
    depends_on:
      - localstack
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - AWS_ENDPOINT=localhost.localstack.cloud:4566
      # - DEBUG=true
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      # - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      # - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      # - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - SERVICES=s3:81
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      # - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        aliases:
          - localhost.localstack.cloud   # set this network aliases to expose localstack to other containers
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3 ls
      interval: 5s
      timeout: 10s
      start_period: 10s
